mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('myuser/', include('myuser.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/myuser/')),
]

myuser/urls.py
from django.urls import path

from . import views

app_name = 'myuser'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('<int:id>/delete', views.delete, name='delete'),
]

myuser/models.py
from django.db import models

# Create your models here.
class MyUser(models.Model):
    username = models.CharField(max_length=50)
    age = models.IntegerField()
    email = models.EmailField()

myuser/forms.py
from django import forms

from .models import MyUser

class PostForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ('username', 'age', 'email')

myuser/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import MyUser
from .forms import PostForm

# Create your views here.
def index(request):
  posts = MyUser.objects.all()
  form = PostForm()
  context = {'posts': posts, 'form': form, }
  return render(request, 'myuser/index.html', context)

def create(request):
  form = PostForm(request.POST)
  form.save(commit=True)
  return HttpResponseRedirect(reverse('myuser:index'))

def delete(request, id=None):
  post = get_object_or_404(MyUser, pk=id)
  post.delete()
  return HttpResponseRedirect(reverse('myuser:index'))

myuser/templates/myuser/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>User List</title>
        <!-- CSS And JavaScript -->
        <link rel="stylesheet"
            href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
        <link rel="stylesheet"
            href="//cdn.rawgit.com/necolas/normalize.css/master/normalize.css">
        <link rel="stylesheet"
            href="//cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css">
    </head>
    <body>
        <div class="container">
            <h1>User List</h1>

            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <form action="{% url 'myuser:create' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="myuser" class="col-sm-3 control-label">Name</label>
                    <div class="col-sm-6">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="myuser" class="col-sm-3 control-label">Age</label>
                    <div class="col-sm-6">
                        {{ form.age }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="myuser" class="col-sm-3 control-label">Email</label>
                    <div class="col-sm-6">
                        {{ form.email }}
                    </div>
                </div>

                <!-- Add User Button -->
                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-6">
                        <button type="submit" class="btn btn-primary">
                            <i class="fa fa-plus"></i> Add User
                        </button>
                    </div>
                </div>

            </form>
            
            <h2>Current Users</h2>
            <table class="table table-striped myuser-table">
                <thead>
                    <th>Name</th><th>age</th><th>Email</th><th> </th>
                </thead>

                <tbody>
                    {% for post in posts %}
                        <tr>
                            <td>
                                <div>{{ post.username }}</div>
                            </td>
                            <td>
                                <div>{{ post.age }}</div>
                            </td>
                            <td>
                                <div>{{ post.email }}</div>
                            </td>
                            <td>
                                <form action="{% url 'myuser:delete' post.id %}" method="post">
                                    {% csrf_token %}
                                    <button>Del user</button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </body>
</html>